cat << EOF > .env
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
MYSQLDB_USER=root
MYSQLDB_ROOT_PASSWORD=123456
MYSQLDB_DATABASE=employeeManagementDb
MYSQLDB_LOCAL_PORT=3307
MYSQLDB_DOCKER_PORT=3306
SPRING_LOCAL_PORT=6868
SPRING_DOCKER_PORT=8080
BUILD_TIME_STAMP= $(date +'%d.%m.%Y.%H.%M.%S ')
EOF
docker-compose up -d