spring:
  datasource: 
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   url: jdbc:mysql://localhost:3306/employmentManagementdb
   password: '123456'
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: 'true'